name: Crash
description: Report a crash in BetterRagnarok (not plugins)
title: Server crashed
body:
  - type: markdown
    attributes:
      value: |
        > [!CAUTION]
        > If the crash can be triggered over the network (e.g. by a player / hack client), DO NOT report it here.
        >
        > Read our [Security Policy](https://github.com/todixx-x/BetterRagnarok/blob/master/SECURITY.md) first.

        > [!TIP]
        > Don't paste raw crashdump data into the issue.
        >
        > Paste it on a site like [GitHub Gist](https://gist.github.com) or [Pastebin](https://pastebin.com).

  - type: input
    id: crashdump-url
    attributes:
      label: Link to crashdump
    validations:
      required: true

  - type: textarea
    attributes:
      label: Additional comments (optional)
      description: Any other information that might help us solve the problem
